from src.utils.parse import Parse
from src.core.state import State

print("=" * 80)
print("OBJECTIVE FUNCTION TESTS")
print("=" * 80)
print()

file_path = "./input/input.json"
parser = Parse(file_path)
data = parser.loadJson()
courses, rooms, students = parser.parseAll(data)

print("Testing each objective function with random initial state...\n")

print("-" * 80)
print("1. STUDENT CONFLICTS OBJECTIVE")
print("-" * 80)
state1 = State(courses, rooms, students, objective='student_conflicts')
state1.initial_state()
penalty1 = state1.calculate_objective()
print(f"Objective: {state1.objective}")
print(f"Penalty: {penalty1}")
print(f"Number of valid operations: {len(state1.successors)}")
print(f"Interpretation: Total hours of time conflicts across all students")
print()

print("-" * 80)
print("2. ROOM CONFLICTS OBJECTIVE")
print("-" * 80)
state2 = State(courses, rooms, students, objective='room_conflicts')
state2.initial_state()
penalty2 = state2.calculate_objective()
print(f"Objective: {state2.objective}")
print(f"Penalty: {penalty2}")
print(f"Number of valid operations: {len(state2.successors)}")
print(f"Interpretation: Weighted penalty for room double-booking (by student priority)")
print()

print("-" * 80)
print("3. CAPACITY OVERFLOW OBJECTIVE")
print("-" * 80)
state3 = State(courses, rooms, students, objective='capacity_overflow')
state3.initial_state()
penalty3 = state3.calculate_objective()
print(f"Objective: {state3.objective}")
print(f"Penalty: {penalty3}")
print(f"Number of valid operations: {len(state3.successors)}")
print(f"Interpretation: Total overflow hours (students beyond room capacity)")
print()

print("=" * 80)
print("SAMPLE SCHEDULE (using student_conflicts objective)")
print("=" * 80)
state1.visualize()

print("=" * 80)
print("TESTING OBJECTIVE CACHING")
print("=" * 80)
print(f"First call: {state3.calculate_objective()}")
print(f"Second call (cached): {state3.calculate_objective()}")
print(f"Cache invalidated after modification...")
operation = state3.get_random_neighbor()
print(f"Random operation: {operation[0]}")
neighbor = state3.copy()
neighbor.execute_operation(operation)
print(f"Neighbor objective: {neighbor.calculate_objective()}")
print()

print("=" * 80)
print("TEST COMPLETED")
print("=" * 80)